#!/usr/bin/env python3
"""Iter039: invariant local-extension jet multiplicities on the K5 cycle space.

This is a representation-theory / power-counting diagnostic. It does not
construct the singular product. It asks whether S5 covariance alone could make
all local extension jets unique over the nominal j=1/2 derivative budget.
"""
from __future__ import annotations
import argparse, itertools, json
from pathlib import Path
import numpy as np

N=5
EDGES=[(i,j) for i in range(N) for j in range(i+1,N)]
EIDX={e:k for k,e in enumerate(EDGES)}

def incidence():
    b=np.zeros((N,len(EDGES)))
    for k,(i,j) in enumerate(EDGES):
        b[i,k]=-1.0; b[j,k]=1.0
    return b

def cycle_basis():
    _,s,vt=np.linalg.svd(incidence(),full_matrices=True)
    rank=int(np.sum(s>1e-12))
    q=vt[rank:].T
    assert q.shape==(10,6)
    return q

def edge_rep(p):
    m=np.zeros((10,10))
    for col,(i,j) in enumerate(EDGES):
        a,bb=p[i],p[j]; sg=1.0
        if a>bb: a,bb=bb,a; sg=-1.0
        m[EIDX[(a,bb)],col]=sg
    return m

def cycle_rep(p,q):
    return q.T@edge_rep(p)@q

def parity(p):
    return sum(p[i]>p[j] for i in range(N) for j in range(i+1,N))%2

def sym_char(r,d):
    # Complete homogeneous symmetric polynomial h_d in eigenvalues of r,
    # generated by Newton recurrence d h_d = sum_{k=1}^d p_k h_{d-k}.
    h=[1.0]+[0.0]*d
    pows=[0.0]+[float(np.trace(np.linalg.matrix_power(r,k))) for k in range(1,d+1)]
    for n in range(1,d+1):
        h[n]=sum(pows[k]*h[n-k] for k in range(1,n+1))/n
    return h[d]

def inv_dim(group,reps,d):
    raw=sum(sym_char(reps[p],d) for p in group)/len(group)
    dim=int(round(raw))
    return dim,float(abs(raw-dim))

def stabilizer(group,sigma):
    out=[]
    for p in group:
        moved=tuple(sigma[p.index(i)] for i in range(N))
        if moved==sigma:
            out.append(p)
    return out

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--degree',type=int,required=True)
    ap.add_argument('--output',type=Path,required=True)
    a=ap.parse_args(); d=a.degree
    if not 0<=d<=16: raise SystemExit('degree must be in [0,16]')
    q=cycle_basis(); s5=list(itertools.permutations(range(N))); a5=[p for p in s5 if parity(p)==0]
    reps={p:cycle_rep(p,q) for p in s5}
    orth=max(float(np.linalg.norm(r.T@r-np.eye(6))) for r in reps.values())
    s5dim,s5res=inv_dim(s5,reps,d); a5dim,a5res=inv_dim(a5,reps,d)
    sigmas={'5+0':(1,1,1,1,1),'4+1':(-1,1,1,1,1),'3+2':(-1,-1,1,1,1)}
    stab={}
    maxres=max(s5res,a5res)
    for name,sig in sigmas.items():
        g=stabilizer(s5,sig); dim,res=inv_dim(g,reps,d); maxres=max(maxres,res)
        stab[name]={'order':len(g),'invariant_dimension':dim,'integrality_residual':res}
    numerical_gates={'cycle_dimension_is_6':q.shape[1]==6,'representation_orthogonal':orth<2e-12,'character_average_integral':maxres<2e-8}
    scientific={'s5_unique_at_degree':s5dim<=1,'a5_unique_at_degree':a5dim<=1}
    result={'iteration':'Iter039','degree':d,'s5_invariant_dimension':s5dim,'a5_invariant_dimension':a5dim,
            'stabilizers':stab,'orthogonality_error':orth,'max_integrality_residual':maxres,
            'numerical_gates':numerical_gates,'scientific_discriminator':scientific,
            'classification':('S5_SYMMETRY_UNIQUE_AT_THIS_DEGREE' if s5dim<=1 else 'S5_SYMMETRY_ONLY_NONUNIQUE_AT_THIS_DEGREE'),
            'claim_lock':'Power-counting/representation result only; not existence, finiteness, or a physical counterterm prescription.'}
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(result,indent=2,sort_keys=True)+'\n')
    print(json.dumps(result,indent=2,sort_keys=True))
    if not all(numerical_gates.values()): raise SystemExit(1)
if __name__=='__main__': main()
